allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
minimumReleaseAgeExclude:
  - tmp@0.2.4
  - tar@7.5.7
  - tar@7.5.3
  - tar@7.5.8
  - tar@7.5.10
  - tar@7.5.11
  - tar@7.5.4
  - webpack-dev-server@5.2.4
  - uuid@11.1.1
  - tmp@0.2.6
