allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
minimumReleaseAgeExclude:
  - webpack-dev-server@5.2.4
  - uuid@11.1.1
  - tmp@0.2.6
